### ISSUE TITLE
While checking for czbaker:request@2.40.0: error: No compatible build found

### ISSUE THREAD

**Issue by rhyslbw** [czbaker/meteor-request#2]
meteor add czbaker:request

"While checking for czbaker:request@2.40.0:
error: No compatible build found"

**Comment by mltucker** [comment]
On OS X, right?  I had the same issue today.  I think the problem is that "fibers" is specified as a dependency, which has native components.  Is this necessary, @czbaker ?  If so, then the solution is to run

    meteor publish-for-arch czbaker:request@2.40.0

on a 64-bit Mac and 32-bit Linux and 64-bit Linux.

**Comment by froatsnook** [comment]
Yes, not required.  See pull request (or install froatsnook:request for now).
